apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: javaimg 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javaimg 
    spec:
      containers:
        - name: javaimg 
          image: anilsiri80cr.azurecr.io/javaimg
          ports:
          - containerPort: 8080